### ISSUE TITLE
Searching doesn't work with uppercase queries

### ISSUE THREAD

**Issue by sethkrasnianski** [astoilkov/jsblocks-shopping-example#4]
Searching exact matches only works with lowercase queries. `dress - silver` works but `Dress - Silver` does not.

Also, when searching `pants ribbon`, I would expect to see the `Pants with a ribbon - Gray/Blue` result... but this isn't as important as the latter.

**Comment by astoilkov** [comment]
Hi,

Thanks for reporting this issues. The first issue is cased from the fact that the filtering function does to call `toLowerCase()` for both parameters. In order to fix the problem you could replace the `searchItems` observable with the code below:

``` javascript
searchItems: Products().extend('filter', function (value) {
  // old code
  // return !!(this.search() && value.title().toLowerCase().indexOf(this.search()) != -1);

  // new code
  return !!(this.search() && value.title().toLowerCase().indexOf(this.search().toLowerCase()) != -1);
}).read()
```

> I will update the code accordingly

About the searching of `pants ribbon`. Yes it is more logical to have the described result included. However, the example project wants to showcase more how to work with the framework and less specifics like effective filtering of data. If you want to make it work you could implement it in the `searchItems` function. You could do something like this:

``` javascript
searchItems: Products().extend('filter', function (value) {
    return !!(this.search() && filterProduct(value.title().toLowerCase(), this.search().toLowerCase()));
}).read()

function filterProduct(title, search) {
    var splits = search.split(' ');
    var result = true;

    blocks.each(splits, function (split) {
        if (title.indexOf(split) == -1) {
            result = false;
            return false;
        }
    });

    return result;
}
```

**Comment by sethkrasnianski** [comment]
:+1:
